name: Build

on:
  pull_request:
  push:
    branches:
      - main
      - develop
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the project
        run: ./gradlew assemble

      - name: Run all checks
        run: ./gradlew check

